CREATE DATABASE movietalk DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

GRANT ALL ON movietalk.* TO 'webproject'@'localhost' IDENTIFIED BY 'test';

use movietalk;

CREATE TABLE users (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	userid VARCHAR(30) NOT NULL UNIQUE,
	name VARCHAR(30) NOT NULL UNIQUE,
	pwd VARCHAR(80) NOT NULL, 
	email VARCHAR(80) NOT NULL
);

CREATE TABLE movies ( 
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	movietitle VARCHAR(100) NOT NULL,
	subtitle VARCHAR(255),
	link VARCHAR(255),
	image VARCHAR(255),
	director VARCHAR(100),
	actor VARCHAR(255),
	pubdate VARCHAR(255),
	userrating FLOAT,
	chattitle VARCHAR(255) UNIQUE,
	opener VARCHAR(30) NOT NULL,
	contents VARCHAR(255),
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chats (
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL,
	writer VARCHAR(30),
	message VARCHAR(255),
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fbusers (
	id int AUTO_INCREMENT PRIMARY KEY, 
	fbid VARCHAR(100) UNIQUE, 
	name VARCHAR(30) NOT NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);